# Generated by Django 3.0.8 on 2020-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('commitid', models.AutoField(primary_key=True, serialize=False)),
                ('committime', models.DateTimeField(auto_now_add=True)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
