# Generated by Django 3.0.8 on 2020-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.CharField(default='Zodiac', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
