# Generated by Django 3.0.8 on 2020-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_auto_20200704_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='username',
            field=models.CharField(default='游客', max_length=20),
        ),
    ]
